name: open_jot
description: "A minimal and open-source journaling app to capture your thoughts, moments, and ideas securely on your device."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  # --- CORE FLUTTER ---
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- STATE MANAGEMENT & ROUTING ---
  get: ^4.7.2

  # --- LOCAL STORAGE ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # --- UI & UX ---
  flutter_quill: ^11.4.2
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  modal_bottom_sheet: ^3.0.0
  progressive_blur: ^0.0.2
  shimmer: ^3.0.0
  smooth_corner: ^1.1.1

  # --- MEDIA & FILE HANDLING ---
  archive: ^4.0.7
  audioplayers: ^6.5.0
  camera: ^0.11.2
  file_picker: ^10.3.2
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  photo_manager: ^3.7.1
  photo_manager_image_provider: ^2.2.0
  printing: ^5.14.2
  record: ^6.1.1
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6

  # --- LOCATION & MAPS ---
  flutter_map: ^8.2.1
  latlong2: ^0.9.0

  # --- SHARING & INTENTS ---
  receive_sharing_intent: ^1.8.1
  share_plus: ^11.1.0

  # --- NOTIFICATIONS ---
  flutter_local_notifications: ^19.4.0
  flutter_timezone: ^4.1.1
  timezone: ^0.10.1

  # --- AUTHENTICATION ---
  local_auth: ^2.2.0

  # --- UTILITIES ---
  device_info_plus: ^11.5.0
  intl: ^0.20.2
  package_info_plus: ^8.3.1
  palette_generator: ^0.3.3+7
  path: ^1.9.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  # --- TESTING ---
  flutter_test:
    sdk: flutter

  # --- CODE ANALYSIS & GENERATION ---
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.svg
    - assets/1.svg
    - assets/2.svg
    - assets/3.svg
    - assets/4.svg
    - assets/5.svg

  fonts:
    - family: OpenRunde
      fonts:
        - asset: assets/fonts/OpenRunde-Regular.otf
        - asset: assets/fonts/OpenRunde-Medium.otf
          weight: 500
        - asset: assets/fonts/OpenRunde-Semibold.otf
          weight: 600
        - asset: assets/fonts/OpenRunde-Bold.otf
          weight: 700
