name: open_jot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6 # Add GetX for state management and routing
  hive: ^2.2.3 # Add Hive for local NoSQL database
  hive_flutter: ^1.1.0 # Add Hive Flutter for Flutter integration
  smooth_corner: ^1.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  modal_bottom_sheet: ^3.0.0
  flutter_quill: ^11.4.2
  intl: ^0.20.2
  permission_handler: ^11.3.1
  photo_manager: ^3.7.1
  shimmer: ^3.0.0
  # Added for audio recording and playback
  record: ^6.0.0
  audioplayers: ^6.5.0
  path_provider: ^2.1.5
  # Added for location and maps
  flutter_map: ^6.1.0  # OpenStreetMap widget
  latlong2: ^0.9.0    # Utility for lat/long coordinates
  geolocator: ^12.0.0 # Get current location
  url_launcher: ^6.3.0 # Launch map link
  path: ^1.9.0
  camera: ^0.11.2
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.2.1
  progressive_blur: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1 # Required for generating Hive adapters
  build_runner: ^2.4.11 # Required for running code generators like hive_generator

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.svg
    - assets/1.svg
    - assets/2.svg
    - assets/3.svg
    - assets/4.svg
    - assets/5.svg


  fonts:
    - family: OpenRunde
      fonts:
        - asset: assets/fonts/OpenRunde-Regular.otf
        - asset: assets/fonts/OpenRunde-Medium.otf
          weight: 500
        - asset: assets/fonts/OpenRunde-Semibold.otf
          weight: 600
        - asset: assets/fonts/OpenRunde-Bold.otf
          weight: 700
