const List<String> reflectionPrompts = [
  "What made you smile today?",
  "Who are you thankful for this week, and why?",
  "What is something small that brought you joy today?",
  "Which part of your day felt most comforting?",
  "What’s something you often take for granted but appreciate now?",
  "What’s the best thing that happened today?",
  "Did someone make your day easier today?",
  "Who made a positive impact on you recently?",
  "What’s a quality you admire in someone close to you?",
  "When did you last feel truly connected with someone?",
  "Who do you want to reach out to soon?",
  "Did someone’s kindness stand out today?",
  "How did you support someone else recently?",
  "Who do you miss the most right now?",
  "What’s a moment from today you want to remember?",
  "What’s a detail about today you might forget if you don’t note it?",
  "What’s the most peaceful moment you had today?",
  "Did you see something beautiful today?",
  "Which memory from this week stands out?",
  "What song, photo, or place will always remind you of today?",
  "What surprised you today?",
  "What challenge did you overcome today?",
  "What’s a small win you had today?",
  "What new thing did you learn about yourself recently?",
  "What are you proud of yourself for?",
  "What habit do you feel good about keeping?",
  "What’s one improvement you’ve noticed in yourself this year?",
  "How did you push yourself out of your comfort zone?",
  "How are you truly feeling right now?",
  "Which emotion stood out the most today?",
  "Did you feel present in any moment today?",
  "When did you feel the most at peace today?",
  "What gave you energy today?",
  "What drained your energy today?",
  "If your mood had a color today, what would it be?",
  "What’s something you’re excited about tomorrow?",
  "What’s one thing you want to improve tomorrow?",
  "What would make tomorrow feel successful?",
  "What do you hope to achieve this week?",
  "What’s a habit you’d like to start tomorrow?",
  "What’s something you want to look forward to in the next month?",
  "What would your ideal tomorrow look like?",
  "What’s one lesson you learned recently?",
  "If you could freeze one moment today, which would it be?",
  "What makes your life feel meaningful right now?",
  "If you described today in one word, what would it be?",
  "What inspired you today?",
  "What did you notice today that you usually overlook?",
  "How has today changed your perspective?",
  "What’s something you’ve been overthinking?",
  "What do you need to let go of?",
  "What part of nature did you notice today?",
  "Did the weather affect your mood today?",
  "What place felt most comforting today?",
  "Where did you feel most at home today?",
  "What sound or smell reminded you of something important?",
  "How did you take care of yourself today?",
  "When did you feel most like yourself today?",
  "What’s something kind you can say to yourself right now?",
  "What do you want to forgive yourself for?",
  "What do you deserve more of in your life?",
];
