on: workflow_dispatch
name: Test, Build and Pre Release apk
env:
  PROPERTIES_PATH: "./android/key.properties"
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Java environment in order to build the Android app.
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17.x'

      # Gradle cache for faster builds
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Setup keystore properties
      - run: |
          echo keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=${{ secrets.ANDROID_KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}

      # Decode Keystore
      - run: echo "${{ secrets.ANDROID_UPLOAD_KEYSTORE }}" | base64 --decode > android/app/key.jks

      # Get flutter dependencies.
      - run: flutter pub get

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Build arm64 APK natively using Gradle
      - name: Build arm64 APK natively using Gradle
        run: |
          cd android
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi
          sed -i 's/\r$//' gradlew
          chmod +x gradlew
          ./gradlew assembleGithubRelease -Ptarget-platform=android-arm64

      # Upload arm64 generated APK
      - name: Upload arm64 APK
        uses: actions/upload-artifact@v4
        with:
          name: OpenJot-arm64-v8a.apk
          path: build/app/outputs/apk/github/release/app-arm64-v8a-github-release.apk