on:
  workflow_dispatch:

name: Test, Build and Release apk

env:
  PROPERTIES_PATH: './android/key.properties'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Extract version from commit message
      - name: Extract version
        id: extract_version
        run: |
          version=$(echo ${{ github.event.head_commit.message }} | grep -oP '(?<=Update: v)\d+\.\d+\.\d+' || echo "0.0.0")
          echo "version=${version}" >> $GITHUB_OUTPUT

      # Setup Java environment in order to build the Android app.
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17.x'

      # Setup the Flutter environment.
      - run: |
          pip install -U yq
          echo "FLUTTER_VERSION=$(yq -r .environment.flutter pubspec.yaml | sed 's/\^//g')" >> $GITHUB_ENV
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: "${{ env.FLUTTER_VERSION }}"

      # Get Flutter dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # --- Signing setup ---
      - name: Decode Keystore File
        run: echo "${{ secrets.ANDROID_UPLOAD_KEYSTORE }}" | base64 --decode > android/app/release-key.jks

      - name: Create Keystore Properties File
        run: |
          echo "storeFile=release-key.jks" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties

      # Statically analyze the Dart code for any errors
      - name: Analyze Dart code
        run: flutter analyze .

      # Build Split APKs natively using Gradle
      - name: Build Split APKs natively using Gradle
        run: |
          cd android
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi
          sed -i 's/\r$//' gradlew
          chmod +x gradlew
          ./gradlew assembleGithubRelease -Psplit-per-abi=true

      # Upload Split generated APKs
      - name: Upload Split APKs
        uses: actions/upload-artifact@v4
        with:
          name: OpenJot-github-splits
          path: ${{ github.workspace }}/build/app/outputs/apk/github/release/*.apk

      # Clean the release directory to prevent the universal artifact from grabbing the splits
      - name: Clean release directory
        run: rm -rf ${{ github.workspace }}/build/app/outputs/apk/github/release/*.apk

      # Build universal APK natively using Gradle
      - name: Build universal APK natively using Gradle
        run: |
          cd android
          ./gradlew assembleGithubRelease

      # Upload universal generated APK using native path
      - name: Upload universal APK
        uses: actions/upload-artifact@v4
        with:
          name: OpenJot-github-universal
          path: ${{ github.workspace }}/build/app/outputs/apk/github/release/*.apk